### ISSUE TITLE
Use chromium instead of firefox

### ISSUE THREAD

**Issue by ximex** [Grisu-NOE/infoscreen-rpi#2]
So we don't need an old browser
https://www.danpurdy.co.uk/web-development/raspberry-pi-kiosk-screen-tutorial/

**Comment by oddest-prime** [comment]
Yes, the next version of infoscreen is not using firefox any more.
Since this is a completely separate project, I am closing the issue in this repository here...

**Comment by pkolmann** [comment]
Do you have a link to the new project?
