### ISSUE TITLE
Update to newer Version?

### ISSUE THREAD

**Issue by prnzngr** [Grisu-NOE/infoscreen-rpi#3]
Is it possible to update this Script to a contemporary one?
It is not working with current Raspbian's

**Comment by oddest-prime** [comment]
I obviously forgot to push the latest commit ;-P
Hopefully this version is still working: https://github.com/Grisu-NOE/infoscreen-rpi/commit/fb8c66ffb16c6f01927fac6567ce892b73718d3c
